language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
env:
  - "RAILS_VERSION=4.0"
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
before_script:
  - psql -c 'create database codaccino_test' -U postgres
